/**
 * Generate dist/sw.js with a precache manifest of the app shell.
 *
 * What gets precached is deliberately narrow: the shell pages (home, about,
 * privacy and 404, in both languages), CSS, and the latin font subsets.
 *
 * What does NOT get precached, and why:
 *   - Tool dependency chunks (transformers.js 802 KB, pdf-lib 425 KB, pdf.js
 *     394 KB, jszip 95 KB, React 182 KB). Precaching these would make a
 *     first-time visitor download the Whisper runtime just for landing on the
 *     homepage, undoing the per-route lazy loading the whole architecture is
 *     built around. They are cached stale-while-revalidate the first time a
 *     page actually pulls them in, which is exactly when they are wanted.
 *   - The ffmpeg core (~31 MB), the ONNX runtime and the Whisper weights
 *     (~39 MB). Cache-first at runtime. Vendor files live under a versioned
 *     path (scripts/versions.mjs), and activation deletes any cached vendor
 *     file that is not under a current version.
 *   - Tool pages. Each is about 30 KB, and with 36 tools in two languages plus
 *     presets, precaching them all cost every first-time visitor well over a
 *     megabyte for pages they will mostly never open. A tool page is cached
 *     the first time it is opened, by the network-first navigation handler.
 *   - Non-latin font subsets. The browser only fetches these if the content
 *     needs them; precaching all of them wastes ~40 KB on every install.
 *
 * The practical result: after one visit the homepage works offline, and any
 * tool works offline once you have opened it once.
 */
import { readdir, writeFile, stat } from 'node:fs/promises';
import { join, relative, extname, basename } from 'node:path';
import { FFMPEG_BASE, ORT_BASE, QPDF_BASE, LIBHEIF_BASE, TESSERACT_BASE, TESSDATA_BASE, LIBREOFFICE_BASE } from './versions.mjs';

const DIST = 'dist';

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

function shouldPrecache(url, file) {
  const ext = extname(file);
  if (url.startsWith('/vendor/')) return false;
  if (ext === '.html') {
    const segments = url.replace(/(\/index)?\.html$/, '').split('/').filter(Boolean);
    const page = segments[0] === 'ms' ? segments.slice(1) : segments;
    return page.length === 0 || (page.length === 1 && ['about', 'privacy', '404'].includes(page[0]));
  }
  if (ext === '.css') return true;
  // Latin subsets only: other scripts are fetched on demand by unicode-range.
  if (ext === '.woff2') return /-latin-wght/.test(basename(file));
  return false;
}

const files = await walk(DIST);
let bytes = 0;
const manifest = [];

for (const file of files) {
  const url = '/' + relative(DIST, file).split('\\').join('/');
  if (!shouldPrecache(url, file)) continue;
  bytes += (await stat(file)).size;
  // Canonical form, no trailing slash: vercel.json 308-redirects /about/ to
  // /about, and a redirected response served to a navigation is an error.
  manifest.push(url === '/index.html' ? '/' : url.replace(/\/index\.html$/, ''));
}

const version = `v${Date.now().toString(36)}`;

const sw = `/* Generated by scripts/build-sw.mjs. Do not edit. */
const VERSION = '${version}';
const SHELL = '${'nhako-shell-'}' + VERSION;
const RUNTIME = 'nhako-runtime';
const VENDOR_CURRENT = ${JSON.stringify([FFMPEG_BASE, ORT_BASE, QPDF_BASE, LIBHEIF_BASE, TESSERACT_BASE, TESSDATA_BASE, LIBREOFFICE_BASE])};
const PRECACHE = ${JSON.stringify(manifest, null, 0)};

// Large WebAssembly and model payloads: cached on first real use, kept
// indefinitely, and deliberately excluded from the precache above.
const RUNTIME_PATTERNS = [
  (url) => url.origin === self.location.origin && url.pathname.startsWith('/vendor/'),
  (url) => url.hostname.endsWith('huggingface.co') || url.hostname.endsWith('hf.co'),
  (url) => url.hostname === 'cdn-lfs.huggingface.co',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(SHELL)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k.startsWith('nhako-shell-') && k !== SHELL).map((k) => caches.delete(k)),
      ))
      // Drop vendor files from superseded versions: tens of MB each.
      .then(() => caches.open(RUNTIME))
      .then(async (cache) => {
        for (const request of await cache.keys()) {
          const { origin, pathname } = new URL(request.url);
          const vendor = origin === self.location.origin && pathname.startsWith('/vendor/');
          if (vendor && !VENDOR_CURRENT.some((base) => pathname.startsWith(base))) await cache.delete(request);
        }
      })
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  // Big binaries: cache-first and never revalidated. That is safe only
  // because every vendor URL carries its package version, so an upgrade is a
  // new URL rather than a changed file.
  if (RUNTIME_PATTERNS.some((match) => match(url))) {
    event.respondWith(
      caches.open(RUNTIME).then(async (cache) => {
        const hit = await cache.match(request);
        if (hit) return hit;
        const response = await fetch(request);
        // Opaque responses have unknown size and can silently blow the quota.
        if (response.ok && response.type !== 'opaque') cache.put(request, response.clone());
        return response;
      }),
    );
    return;
  }

  if (url.origin !== self.location.origin) return;

  // Analytics script and beacons: always straight to the network, never cached.
  if (url.pathname.startsWith('/_vercel/')) return;

  // Navigations: network-first so a deploy is picked up immediately, with the
  // cache as the offline fallback.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(SHELL).then((c) => c.put(request, copy));
          return response;
        })
        .catch(async () => (await caches.match(request)) ?? (await caches.match('/')) ?? Response.error()),
    );
    return;
  }

  // Static assets: stale-while-revalidate.
  event.respondWith(
    caches.open(SHELL).then(async (cache) => {
      const hit = await cache.match(request);
      const network = fetch(request)
        .then((response) => {
          if (response.ok) cache.put(request, response.clone());
          return response;
        })
        .catch(() => hit);
      return hit ?? network;
    }),
  );
});
`;

await writeFile(join(DIST, 'sw.js'), sw);
console.log(`[build-sw] precaching ${manifest.length} shell files (${(bytes / 1024).toFixed(0)} KB); vendor + model runtime-cached`);
