import type { Locale } from '../../i18n/paths';

const en = {
  // Script
  library: 'Script',
  untitled: 'Untitled script',
  newScript: 'New',
  deleteScript: 'Delete',
  confirmDelete: (title: string) => `Delete "${title}"? This cannot be undone.`,
  importFile: 'Import .txt, .md or .docx',
  importFailed: 'That file could not be read as text. Try .txt, .md or .docx.',
  title: 'Title',
  scriptLabel: 'Your script',
  placeholder: 'Type or paste your script here…',
  stats: (words: number, time: string, wpm: number) => `${words} word${words === 1 ? '' : 's'} · about ${time} at ${wpm} wpm`,
  sectionsCount: (n: number) => `${n} section${n === 1 ? '' : 's'}`,
  pausesCount: (n: number) => `${n} pause${n === 1 ? '' : 's'}`,
  savedHere: 'Saved in this browser as you type.',
  formatHelp: 'Formatting',
  formatRows: [
    ['# Heading', 'starts a section you can jump to'],
    ['[PAUSE]', 'stops the scroll there until you continue'],
    ['[SMILE]', 'any other word in brackets is a note to you, shown but not read'],
    ['**words**', 'highlighted for emphasis'],
    ['a blank line', 'starts a new paragraph'],
  ] as [string, string][],
  // Settings
  settings: 'Display and speed',
  speed: 'Speed',
  wpmUnit: 'wpm',
  fontSize: 'Text size',
  lineHeight: 'Line spacing',
  margin: 'Side margins',
  guide: 'Reading line',
  guideHelp: 'How far down the screen you read. Keep it high, just under the camera, so your eyes stay near the lens.',
  theme: 'Colours',
  themes: { dark: 'White on black', light: 'Black on white', yellow: 'Yellow on black' },
  align: 'Alignment',
  aligns: { left: 'Left', center: 'Centre' },
  mirrorX: 'Mirror (for a beam-splitter rig)',
  mirrorY: 'Flip upside down',
  countdown: 'Countdown',
  countdownOff: 'None',
  seconds: (n: number) => `${n} s`,
  voice: 'Voice-follow: scroll as I speak',
  voiceHelp: 'Uses your browser\'s speech recognition. In Chrome and Edge your voice is sent to Google\'s speech service while it listens, and Safari may use Apple\'s. It is off unless you tick this, and never remembered as on.',
  voiceLang: 'Language you will speak',
  voiceNone: 'This browser has no speech recognition. Try Chrome, Edge or Safari.',
  // Start
  start: 'Start',
  startRecord: 'Start and record',
  keysTitle: 'Keyboard, pedal and page-turner keys',
  keys: [
    ['Space, Enter, B or K', 'play or pause'],
    ['↑ ↓', 'move back or forward a line'],
    ['Page Up, Page Down', 'previous or next section'],
    ['← →, − +', 'slower or faster'],
    ['R', 'start or stop recording'],
    ['Home', 'back to the start'],
    ['Esc', 'close'],
  ] as [string, string][],
  keysNote: 'Most Bluetooth page turners send Page Up and Page Down, and most foot pedals can be set to send Space.',
  // Takes
  takes: 'Recordings',
  noTakes: 'Recordings you make appear here. They stay on this device.',
  download: 'Download',
  play: 'Play',
  deleteTake: 'Delete',
  confirmDeleteTake: (name: string) => `Delete ${name}? This cannot be undone.`,
  inMemory: 'Not saved on the device. Download it before you close this page.',
  onDevice: 'Stored on this device',
  // Stage
  stageLabel: 'Teleprompter',
  empty: 'There is nothing to read yet. Close this and type a script.',
  pause: 'Pause',
  slower: 'Slower',
  faster: 'Faster',
  prevSection: 'Previous section',
  nextSection: 'Next section',
  restart: 'Restart',
  pausedAtCue: 'Paused at a cue. Tap to continue.',
  left: (time: string) => `${time} left`,
  listening: 'Listening',
  voiceUnsupported: 'No voice-follow in this browser',
  voiceBlocked: 'Microphone blocked for voice-follow',
  record: 'Record',
  stopRecording: 'Stop recording',
  rec: 'REC',
  preview: 'Camera',
  remote: 'Phone remote',
  close: 'Close',
  dismiss: 'Dismiss',
  cameraBlocked: 'Camera or microphone access was blocked. Allow it in your browser\'s site settings, then try again.',
  cameraMissing: 'No camera or microphone was found.',
  recordUnsupported: 'This browser cannot record video.',
  recordFailed: 'Recording stopped unexpectedly. The device may be out of space.',
  takeSaved: (name: string) => `Saved ${name} on this device.`,
  takeInMemory: (name: string) => `${name} is ready. Download it before you close the page: this browser cannot store it.`,
  remoteTitle: 'Use your phone as a remote',
  remoteHelp: 'Scan this with your phone\'s camera, or open the address below and type the code.',
  orOpen: 'Or open',
  phoneConnected: 'Phone connected.',
  waitingPhone: 'Waiting for your phone…',
  relayOffline: 'Cannot reach the relay. Check the internet connection.',
  connecting: 'Connecting…',
  remotePrivacy: 'Only button presses (play, pause, speed) pass between the devices, through a relay run by Supabase. Your script, video and audio never leave this tablet.',
  done: 'Done',
  // Remote page
  remotePage: {
    title: 'Teleprompter remote',
    codeLabel: 'Room code',
    codeHelp: 'The 10-character code shown on the teleprompter.',
    join: 'Connect',
    badCode: 'That code should be 10 letters and numbers.',
    searching: 'Looking for the teleprompter…',
    found: 'Connected',
    lost: 'The teleprompter is not answering. Check that it is still open.',
    offline: 'Cannot reach the relay. Check your internet connection.',
    playPause: 'Play / pause',
    playing: 'Playing',
    paused: 'Paused',
    back: 'Back',
    forward: 'Forward',
    prev: 'Previous section',
    next: 'Next section',
    restart: 'Restart',
    record: 'Record',
    stopRecording: 'Stop recording',
    recording: 'Recording',
    left: (time: string) => `${time} left`,
    leave: 'Disconnect',
  },
};

const ms: typeof en = {
  library: 'Skrip',
  untitled: 'Skrip tanpa tajuk',
  newScript: 'Baharu',
  deleteScript: 'Padam',
  confirmDelete: (title) => `Padam "${title}"? Tindakan ini tidak boleh dibatalkan.`,
  importFile: 'Import .txt, .md atau .docx',
  importFailed: 'Fail itu tidak dapat dibaca sebagai teks. Cuba .txt, .md atau .docx.',
  title: 'Tajuk',
  scriptLabel: 'Skrip anda',
  placeholder: 'Taip atau tampal skrip anda di sini…',
  stats: (words, time, wpm) => `${words} perkataan · kira-kira ${time} pada ${wpm} ppm`,
  sectionsCount: (n) => `${n} bahagian`,
  pausesCount: (n) => `${n} jeda`,
  savedHere: 'Disimpan dalam pelayar ini semasa anda menaip.',
  formatHelp: 'Pemformatan',
  formatRows: [
    ['# Tajuk', 'memulakan bahagian yang boleh anda lompat ke'],
    ['[PAUSE] atau [JEDA]', 'menghentikan tatalan di situ sehingga anda teruskan'],
    ['[SENYUM]', 'perkataan lain dalam kurungan ialah nota untuk anda, dipaparkan tetapi tidak dibaca'],
    ['**perkataan**', 'diserlahkan untuk penekanan'],
    ['baris kosong', 'memulakan perenggan baharu'],
  ],
  settings: 'Paparan dan kelajuan',
  speed: 'Kelajuan',
  wpmUnit: 'ppm',
  fontSize: 'Saiz teks',
  lineHeight: 'Jarak baris',
  margin: 'Jidar sisi',
  guide: 'Garis bacaan',
  guideHelp: 'Sejauh mana ke bawah skrin anda membaca. Letakkan tinggi, tepat di bawah kamera, supaya mata anda kekal dekat dengan kanta.',
  theme: 'Warna',
  themes: { dark: 'Putih atas hitam', light: 'Hitam atas putih', yellow: 'Kuning atas hitam' },
  align: 'Penjajaran',
  aligns: { left: 'Kiri', center: 'Tengah' },
  mirrorX: 'Cermin (untuk rig pemisah cahaya)',
  mirrorY: 'Terbalikkan',
  countdown: 'Kira detik',
  countdownOff: 'Tiada',
  seconds: (n) => `${n} s`,
  voice: 'Ikut suara: tatal semasa saya bercakap',
  voiceHelp: 'Menggunakan pengecaman pertuturan pelayar anda. Dalam Chrome dan Edge, suara anda dihantar ke perkhidmatan pertuturan Google semasa ia mendengar, dan Safari mungkin menggunakan perkhidmatan Apple. Ia dimatikan melainkan anda tandakan ini, dan tidak pernah diingat sebagai hidup.',
  voiceLang: 'Bahasa yang akan anda tuturkan',
  voiceNone: 'Pelayar ini tiada pengecaman pertuturan. Cuba Chrome, Edge atau Safari.',
  start: 'Mula',
  startRecord: 'Mula dan rakam',
  keysTitle: 'Kekunci papan kekunci, pedal dan pemusing halaman',
  keys: [
    ['Space, Enter, B atau K', 'main atau jeda'],
    ['↑ ↓', 'undur atau maju satu baris'],
    ['Page Up, Page Down', 'bahagian sebelum atau seterusnya'],
    ['← →, − +', 'lebih perlahan atau lebih laju'],
    ['R', 'mula atau henti rakaman'],
    ['Home', 'kembali ke permulaan'],
    ['Esc', 'tutup'],
  ],
  keysNote: 'Kebanyakan pemusing halaman Bluetooth menghantar Page Up dan Page Down, dan kebanyakan pedal kaki boleh ditetapkan untuk menghantar Space.',
  takes: 'Rakaman',
  noTakes: 'Rakaman yang anda buat dipaparkan di sini. Ia kekal pada peranti ini.',
  download: 'Muat turun',
  play: 'Main',
  deleteTake: 'Padam',
  confirmDeleteTake: (name) => `Padam ${name}? Tindakan ini tidak boleh dibatalkan.`,
  inMemory: 'Tidak disimpan pada peranti. Muat turun sebelum anda menutup halaman ini.',
  onDevice: 'Disimpan pada peranti ini',
  stageLabel: 'Teleprompter',
  empty: 'Belum ada apa-apa untuk dibaca. Tutup ini dan taip skrip.',
  pause: 'Jeda',
  slower: 'Lebih perlahan',
  faster: 'Lebih laju',
  prevSection: 'Bahagian sebelum',
  nextSection: 'Bahagian seterusnya',
  restart: 'Mula semula',
  pausedAtCue: 'Dijeda pada isyarat. Ketik untuk teruskan.',
  left: (time) => `${time} lagi`,
  listening: 'Mendengar',
  voiceUnsupported: 'Tiada ikut suara dalam pelayar ini',
  voiceBlocked: 'Mikrofon disekat untuk ikut suara',
  record: 'Rakam',
  stopRecording: 'Henti rakam',
  rec: 'REC',
  preview: 'Kamera',
  remote: 'Alat kawalan telefon',
  close: 'Tutup',
  dismiss: 'Tutup',
  cameraBlocked: 'Akses kamera atau mikrofon disekat. Benarkannya dalam tetapan laman pelayar anda, kemudian cuba lagi.',
  cameraMissing: 'Tiada kamera atau mikrofon ditemui.',
  recordUnsupported: 'Pelayar ini tidak boleh merakam video.',
  recordFailed: 'Rakaman berhenti tanpa diduga. Ruang storan peranti mungkin sudah penuh.',
  takeSaved: (name) => `${name} disimpan pada peranti ini.`,
  takeInMemory: (name) => `${name} sudah sedia. Muat turun sebelum anda menutup halaman: pelayar ini tidak dapat menyimpannya.`,
  remoteTitle: 'Guna telefon anda sebagai alat kawalan',
  remoteHelp: 'Imbas ini dengan kamera telefon anda, atau buka alamat di bawah dan taip kodnya.',
  orOpen: 'Atau buka',
  phoneConnected: 'Telefon disambungkan.',
  waitingPhone: 'Menunggu telefon anda…',
  relayOffline: 'Tidak dapat mencapai geganti. Semak sambungan internet.',
  connecting: 'Menyambung…',
  remotePrivacy: 'Hanya tekanan butang (main, jeda, kelajuan) dihantar antara peranti, melalui geganti yang dikendalikan oleh Supabase. Skrip, video dan audio anda tidak pernah meninggalkan tablet ini.',
  done: 'Selesai',
  remotePage: {
    title: 'Alat kawalan teleprompter',
    codeLabel: 'Kod bilik',
    codeHelp: 'Kod 10 aksara yang dipaparkan pada teleprompter.',
    join: 'Sambung',
    badCode: 'Kod itu sepatutnya 10 huruf dan nombor.',
    searching: 'Mencari teleprompter…',
    found: 'Disambungkan',
    lost: 'Teleprompter tidak menjawab. Pastikan ia masih dibuka.',
    offline: 'Tidak dapat mencapai geganti. Semak sambungan internet anda.',
    playPause: 'Main / jeda',
    playing: 'Sedang main',
    paused: 'Dijeda',
    back: 'Undur',
    forward: 'Maju',
    prev: 'Bahagian sebelum',
    next: 'Bahagian seterusnya',
    restart: 'Mula semula',
    record: 'Rakam',
    stopRecording: 'Henti rakam',
    recording: 'Merakam',
    left: (time) => `${time} lagi`,
    leave: 'Putuskan sambungan',
  },
};

export const PROMPTER_TEXT: Record<Locale, typeof en> = { en, ms };
export type PrompterText = typeof en;
export type StageText = PrompterText;

export const SAMPLE: Record<Locale, string> = {
  en: `# Welcome
This is your teleprompter. Replace this text with your own script, or import a file.

Set a speed in **words per minute**, then press Start. [SMILE]

# Controls
Tap the screen, or press the space bar, to pause and carry on. [PAUSE]

A Bluetooth page turner, a foot pedal or your phone can control it too, so you never have to touch the screen on camera.

# Recording
Press Start and record to film yourself as you read. The video stays on this device.`,
  ms: `# Selamat datang
Ini teleprompter anda. Gantikan teks ini dengan skrip anda sendiri, atau import fail.

Tetapkan kelajuan dalam **perkataan seminit**, kemudian tekan Mula. [SENYUM]

# Kawalan
Ketik skrin, atau tekan bar ruang, untuk menjeda dan meneruskan. [JEDA]

Pemusing halaman Bluetooth, pedal kaki atau telefon anda juga boleh mengawalnya, jadi anda tidak perlu menyentuh skrin semasa dirakam.

# Rakaman
Tekan Mula dan rakam untuk merakam diri anda semasa membaca. Video kekal pada peranti ini.`,
};
