import type { ToolMeta } from './types';

/**
 * THE SOURCE OF TRUTH.
 *
 * Routes, page metadata, the homepage grid, the command palette and the sitemap
 * are all derived from this array. A tool that is not here has no page, and a
 * duplicate id fails the build (see registry.test.ts), which structurally
 * eliminates the four bugs the old build shipped: a dead `css-generator` slug
 * that rendered a working-looking page doing nothing, a dead `edit-pdf`,
 * `convert-pdf` listed twice, and `/tool/<anything>` returning a real page.
 */
export const TOOLS: readonly ToolMeta[] = [
  // ─── PDF ──────────────────────────────────────────────────────────────────
  {
    slug: 'merge', category: 'pdf', name: 'Merge PDF', kind: 'app', group: 'organise',
    blurb: 'Combine several PDFs, in an order you set.',
    description: 'Merge PDF files in your browser. No upload, no file size limit, no account. Drop the files and the merged PDF is ready instantly.',
    keywords: ['merge', 'combine', 'join', 'concatenate', 'append', 'pdf'],
    accept: 'application/pdf,.pdf', multiple: true,
    about: 'Dropped files are staged as a row of thumbnails that you drag into the order you want before anything runs. Every page keeps its original size and quality, and nothing is re-encoded, so the output is lossless.',
    limits: ['Encrypted or password-protected PDFs must be unlocked first.', 'Very large merges are bounded by your device memory, not by an upload cap.'],
    related: ['pdf/split', 'pdf/compress', 'pdf/rotate'],
  },
  {
    slug: 'split', category: 'pdf', name: 'Split PDF', kind: 'app', group: 'organise',
    blurb: 'Tick the pages you want and split them out.',
    description: 'Split a PDF in your browser. Every page is shown with a tick box, so you pick what to extract without typing a page range. No upload and no page limit.',
    keywords: ['split', 'separate', 'extract pages', 'divide', 'burst', 'select pages', 'pdf'],
    accept: 'application/pdf,.pdf',
    /* Still declared, although Split PDF now draws its own page grid: these
       are the engine's inputs, and the app compiles its tick boxes straight
       into `range`. Keeping them here keeps the tool self-describing, and
       keeps the worker path honest about what it accepts. */
    options: [
      { kind: 'text', key: 'range', label: 'Pages', default: '', placeholder: 'all, or 1-5, 8, 11-13', help: 'Leave empty to split every page.' },
      { kind: 'select', key: 'mode', label: 'Split into', default: 'each', choices: [
        { value: 'each', label: 'One file per page' },
        { value: 'one', label: 'One PDF of the selected pages' },
      ] },
    ],
    about: 'Every page is drawn with a tick box, so the pages are chosen by looking rather than by typing a range. Tick what you want, then either cut each page into its own PDF, delivered as a ZIP, or keep the selection together as one new PDF. Pages are copied, not re-rendered, so quality is untouched.',
    limits: ['One file per page arrives as a ZIP, even when only one page is ticked.'],
    related: ['pdf/merge', 'pdf/rotate', 'pdf/to-image'],
  },
  {
    slug: 'rotate', category: 'pdf', name: 'Rotate PDF', kind: 'file', group: 'organise',
    blurb: 'Rotate pages and fix orientation.',
    description: 'Rotate PDF pages in your browser. Fix sideways or upside-down scans without uploading the file.',
    keywords: ['rotate', 'turn', 'orientation', 'sideways', 'upside down', 'landscape', 'portrait', 'edit'],
    accept: 'application/pdf,.pdf',
    options: [
      { kind: 'select', key: 'angle', label: 'Rotate by', default: '90', choices: [
        { value: '90', label: '90° clockwise' }, { value: '180', label: '180°' }, { value: '270', label: '90° anticlockwise' },
      ] },
      { kind: 'text', key: 'range', label: 'Pages', default: '', placeholder: 'all, or 1-5, 8', help: 'Leave empty to rotate every page.' },
    ],
    about: 'Rotation is applied to the page metadata, so nothing is re-rendered and quality is untouched.',
    limits: ['Rotation is a multiple of 90°. Arbitrary angles would require rasterising the page.'],
    related: ['pdf/split', 'pdf/merge', 'pdf/watermark'],
  },
  {
    slug: 'organize', category: 'pdf', name: 'Organize PDF', kind: 'app', group: 'organise',
    blurb: 'Reorder, rotate and delete pages.',
    description: 'Reorder, rotate and delete PDF pages by dragging thumbnails in your browser. Combine several PDFs while you are at it. No upload.',
    keywords: ['organize', 'organise', 'reorder', 'rearrange', 'delete pages', 'remove pages', 'move pages', 'sort', 'arrange'],
    accept: 'application/pdf,.pdf',
    about: 'Every page shows as a thumbnail. Drag to reorder, or use the buttons on each page; rotate or remove pages; add more PDFs and they join the end. Pages are copied, not re-rendered, so nothing loses quality.',
    limits: ['Password-protected PDFs must be unlocked first.', 'Very long documents take a moment to draw every thumbnail.'],
    related: ['pdf/merge', 'pdf/split', 'pdf/rotate'],
  },
  {
    slug: 'crop', category: 'pdf', name: 'Crop PDF', kind: 'file', group: 'organise',
    blurb: 'Trim margins off every page.',
    description: 'Crop PDF pages in your browser by trimming margins from any side. Lossless, nothing is re-rendered, and nothing is uploaded.',
    keywords: ['crop', 'trim', 'margins', 'cut', 'resize page', 'whitespace'],
    accept: 'application/pdf,.pdf',
    options: [
      { kind: 'number', key: 'top', label: 'Top', min: 0, max: 150, step: 1, default: 10, suffix: 'mm' },
      { kind: 'number', key: 'bottom', label: 'Bottom', min: 0, max: 150, step: 1, default: 10, suffix: 'mm' },
      { kind: 'number', key: 'left', label: 'Left', min: 0, max: 150, step: 1, default: 10, suffix: 'mm' },
      { kind: 'number', key: 'right', label: 'Right', min: 0, max: 150, step: 1, default: 10, suffix: 'mm' },
      { kind: 'text', key: 'range', label: 'Pages', default: '', placeholder: 'all, or 1-5, 8', help: 'Leave empty to crop every page.' },
    ],
    about: 'Changes each page\'s visible area (its crop box). Nothing is re-rendered, so text stays sharp and selectable. Margins are measured on the page as you see it, including pages stored sideways.',
    limits: ['Cropping hides content; it does not delete it. The trimmed area is still inside the file, and some editors can reveal it. Do not rely on cropping to remove sensitive information.'],
    related: ['pdf/organize', 'pdf/compress', 'image/crop'],
  },

  {
    slug: 'jpg-to-pdf', category: 'pdf', name: 'JPG to PDF', kind: 'app', group: 'convert', alsoIn: [{ category: 'image', group: 'convert' }],
    blurb: 'Arrange photos, then turn them into a PDF.',
    description: 'Convert JPG, PNG and other images to a PDF in your browser, one page each. JPG and PNG go in without recompression. No upload.',
    keywords: ['jpg to pdf', 'image to pdf', 'png to pdf', 'photo to pdf', 'convert', 'scan', 'pictures'],
    accept: 'image/*', multiple: true,
    options: [
      { kind: 'select', key: 'page', label: 'Page size', default: 'a4', choices: [
        { value: 'a4', label: 'A4' }, { value: 'letter', label: 'US Letter' }, { value: 'fit', label: 'Same as the image' },
      ] },
      { kind: 'select', key: 'orientation', label: 'Orientation', default: 'auto', when: [{ key: 'page', equals: 'a4' }], choices: [
        { value: 'auto', label: 'Match each image' }, { value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' },
      ] },
      { kind: 'select', key: 'margin', label: 'Margin', default: '0', choices: [
        { value: '0', label: 'None' }, { value: '10', label: '10 mm' }, { value: '20', label: '20 mm' },
      ] },
    ],
    about: 'Each image becomes a page, in the order you drop them. JPG and PNG are embedded as they are, so the PDF looks exactly like the originals. Phone photos that are only turned by their EXIF tag are straightened first, because a PDF ignores that tag.',
    limits: ['Images are placed in the order they are dropped. Reorder the pages afterwards with Organize PDF.', 'Formats a PDF cannot hold directly (WebP, GIF, BMP) are converted to high-quality JPG on the way in.'],
    related: ['pdf/organize', 'pdf/compress', 'image/heic-to-jpg'],
  },
  {
    slug: 'to-image', category: 'pdf', name: 'PDF to JPG', kind: 'file', group: 'convert', alsoIn: [{ category: 'image', group: 'convert' }],
    blurb: 'Turn every page into a high-resolution image.',
    description: 'Convert PDF pages to JPG or PNG in your browser. High resolution, no upload, no watermark.',
    keywords: ['pdf to jpg', 'pdf to png', 'pdf to image', 'convert', 'render', 'export', 'screenshot'],
    accept: 'application/pdf,.pdf',
    options: [
      { kind: 'select', key: 'format', label: 'Format', default: 'jpg', choices: [{ value: 'jpg', label: 'JPG' }, { value: 'png', label: 'PNG' }] },
      { kind: 'select', key: 'scale', label: 'Resolution', default: '2', choices: [
        { value: '1', label: '72 dpi, screen' }, { value: '2', label: '144 dpi, default' }, { value: '3', label: '216 dpi, print' },
      ] },
    ],
    about: 'Each page is rendered at the chosen resolution and exported as an image, bundled into a ZIP.',
    limits: ['High resolutions on long documents are memory-hungry.'],
    related: ['pdf/to-text', 'image/convert', 'pdf/compress'],
  },
  {
    slug: 'office-to-pdf', category: 'pdf', name: 'Office to PDF', kind: 'file', group: 'convert', heavy: true, multiple: true,
    seoTitle: 'Word, Excel, PowerPoint to PDF online, free, no upload | Nhako Tools',
    blurb: 'Word, Excel and PowerPoint to PDF.',
    description: 'Convert Word, Excel and PowerPoint files to PDF in your browser with LibreOffice. The conversion runs on your device, so documents are never uploaded.',
    keywords: ['word to pdf', 'docx to pdf', 'excel to pdf', 'xlsx to pdf', 'powerpoint to pdf', 'pptx to pdf', 'doc to pdf', 'office to pdf', 'odt to pdf', 'convert to pdf', 'libreoffice'],
    accept: '.doc,.docx,.odt,.rtf,.txt,.xls,.xlsx,.ods,.csv,.ppt,.pptx,.odp',
    about: 'LibreOffice, the open-source office suite, compiled to run inside your browser, opens each file and exports it as PDF, exactly as it would on a desktop. Several files at once come back as a ZIP. The engine is downloaded from this site the first time, then kept by your browser, so later conversions start straight away.',
    limits: ['The first use downloads LibreOffice once: about 77 MB, and it needs about 1 GB of free memory. A desktop or laptop browser is recommended; many phones cannot run it.', 'Layout is LibreOffice\'s reading of the file. It is usually very close to Office, but fonts Office has and LibreOffice does not are replaced by similar ones, which can move line breaks.', 'Password-protected files must have their password removed first.'],
    related: ['pdf/to-word', 'pdf/merge', 'pdf/compress'],
    variants: [
      { slug: 'word', short: 'Word', name: 'Word to PDF', blurb: 'Convert .docx and .doc files to PDF.', defaults: {},
        description: 'Convert Word documents (.docx, .doc) to PDF in your browser with LibreOffice. Free, no upload, no watermark, no account.' },
      { slug: 'excel', short: 'Excel', name: 'Excel to PDF', blurb: 'Convert .xlsx and .xls spreadsheets to PDF.', defaults: {},
        description: 'Convert Excel spreadsheets (.xlsx, .xls, .csv) to PDF in your browser with LibreOffice. Free, no upload, no watermark, no account.' },
      { slug: 'powerpoint', short: 'PowerPoint', name: 'PowerPoint to PDF', blurb: 'Convert .pptx and .ppt slides to PDF.', defaults: {},
        description: 'Convert PowerPoint presentations (.pptx, .ppt) to PDF in your browser with LibreOffice. Free, no upload, no watermark, no account.' },
    ],
  },
  {
    slug: 'to-word', category: 'pdf', name: 'PDF to Word', kind: 'file', group: 'convert',
    blurb: 'Turn a PDF into an editable Word document.',
    description: 'Convert PDF to an editable Word document (.docx) in your browser, with paragraphs, headings, bold and italic rebuilt. No upload, no account, no watermark.',
    keywords: ['pdf to word', 'pdf to docx', 'convert pdf to word', 'editable', 'edit pdf text', 'pdf to doc', 'word', 'docx'],
    accept: 'application/pdf,.pdf',
    about: 'Reads each page\'s text with its position, size and font, rebuilds lines into paragraphs and headings the way you would read them, and writes a real .docx with bold, italic, fonts and page breaks. The result is text you can edit, not pictures of the pages.',
    limits: ['Images, tables, columns and colours are not carried over: this gets you the text and its structure, to edit or reuse. For an exact visual copy, keep the PDF.', 'Scanned PDFs have no text to convert. Run them through OCR PDF first.', 'Unusual layouts, like text in several columns or around pictures, may come out in the wrong order.'],
    related: ['pdf/office-to-pdf', 'pdf/ocr', 'pdf/to-text'],
  },
  {
    slug: 'to-text', category: 'pdf', name: 'PDF to text', kind: 'file', group: 'convert',
    blurb: 'Extract the raw text from a PDF.',
    description: 'Extract text from a PDF in your browser. No upload, no account, no character limit.',
    keywords: ['pdf to text', 'extract text', 'copy text', 'txt', 'scrape', 'read'],
    accept: 'application/pdf,.pdf',
    about: 'Pulls the embedded text layer out of the document, page by page.',
    limits: ['Scanned PDFs have no text layer, so this returns nothing for them. OCR is not included.', 'Complex multi-column layouts may extract out of reading order.'],
    related: ['pdf/to-image', 'media/transcribe', 'dev/word-count'],
  },
  {
    slug: 'ocr', category: 'pdf', name: 'OCR PDF', kind: 'file', group: 'convert', heavy: true,
    seoTitle: 'OCR PDF online: make a scanned PDF searchable, free | Nhako Tools',
    blurb: 'Make a scanned PDF searchable and copyable.',
    description: 'Make a scanned PDF searchable in your browser: the text is recognised on your device, in English or Malay, and laid invisibly over each page. No upload.',
    keywords: ['ocr', 'ocr pdf', 'searchable pdf', 'scanned pdf', 'recognise text', 'recognize text', 'copy text from scan', 'text recognition', 'imbasan'],
    accept: 'application/pdf,.pdf',
    options: [
      { kind: 'select', key: 'language', label: 'Language', default: 'eng+msa', choices: [
        { value: 'eng+msa', label: 'English and Malay' }, { value: 'eng', label: 'English' }, { value: 'msa', label: 'Malay' },
      ], help: 'Choosing only the language on the page is a little faster and more accurate.' },
      { kind: 'toggle', key: 'skipText', label: 'Skip pages that already have text', default: true },
    ],
    about: 'Each page is drawn at about 300 dpi and read by Tesseract, running in your browser, in English, Malay or both. The words are laid over the original page as invisible text, as a scanner does, so the page looks exactly the same but you can now search, select and copy it. The recognised text is shown too, ready to copy.',
    limits: ['The first run downloads the OCR engine and language data once, about 15 MB, from this site.', 'Accuracy depends on the scan: skewed, blurred, low-resolution or handwritten pages read poorly.', 'Tables and columns come out as plain lines of text in the copy, although the invisible layer sits over the right words.', 'Large documents take a while: around a few seconds per page.'],
    related: ['image/ocr', 'pdf/to-text', 'pdf/compress'],
  },
  {
    slug: 'scan', category: 'pdf', name: 'Scan to PDF', kind: 'app', group: 'convert',
    seoTitle: 'Scan to PDF with your phone camera, free, no upload | Nhako Tools',
    blurb: 'Photograph pages and get a clean PDF.',
    description: 'Turn phone photos of documents into a clean PDF: the page is found, straightened and whitened on your device. Several pages, A4 or Letter. No upload, no app.',
    keywords: ['scan to pdf', 'scanner', 'camera scanner', 'document scanner', 'photo to pdf', 'scan document', 'camscanner', 'phone scan', 'imbas'],
    accept: 'image/*',
    about: 'Take a photo, or choose some, and each page is found in the picture, straightened as if scanned flat, and cleaned up: shadows lifted to a white page, in grey, black and white, or the original colour. Adjust the corners if the page was not found exactly, put the pages in order, and save one PDF.',
    limits: ['Finding the page works best with the whole sheet in view on a darker surface. On a white table, set the corners by hand.', 'This straightens a flat page. A curled book spine stays curved.', 'The PDF is pictures of the pages. To make the text searchable too, run it through OCR PDF.'],
    related: ['pdf/ocr', 'pdf/jpg-to-pdf', 'pdf/compress'],
  },
  {
    slug: 'watermark', category: 'pdf', name: 'Watermark PDF', kind: 'file', group: 'mark-up',
    blurb: 'Stamp text across every page.',
    description: 'Add a text watermark to a PDF in your browser. Set the text, size, angle and opacity. Nothing is uploaded.',
    keywords: ['watermark', 'stamp', 'draft', 'confidential', 'overlay', 'brand'],
    accept: 'application/pdf,.pdf',
    options: [
      { kind: 'text', key: 'text', label: 'Text', default: 'DRAFT', placeholder: 'DRAFT' },
      { kind: 'range', key: 'size', label: 'Size', min: 10, max: 120, step: 2, default: 52, suffix: 'pt' },
      { kind: 'range', key: 'opacity', label: 'Opacity', min: 5, max: 100, step: 5, default: 20, suffix: '%' },
      { kind: 'range', key: 'angle', label: 'Angle', min: -90, max: 90, step: 15, default: 45, suffix: '°' },
    ],
    about: 'Draws the text once per page, centred. It sits on top of the existing content.',
    limits: ['Text watermarks only. Image watermarks are not supported.', 'Latin characters only. The stamp uses a built-in PDF font, which cannot draw Cyrillic, Greek, CJK or emoji.', 'A watermark is not security: it can be removed by anyone with the right tool.'],
    related: ['pdf/rotate', 'pdf/merge', 'pdf/compress'],
  },
  {
    slug: 'sign', category: 'pdf', name: 'Sign PDF', kind: 'app', group: 'mark-up',
    blurb: 'Draw or type a signature and place it.',
    description: 'Sign a PDF in your browser: draw, type or upload a signature, place it on any page, and save. Your signature never leaves your device.',
    keywords: ['sign', 'signature', 'e-sign', 'esign', 'autograph', 'initial', 'fill', 'tandatangan'],
    accept: 'application/pdf,.pdf',
    about: 'Draw with a mouse, finger or stylus, type your name in a handwriting font, or use a photo of your signature. Click a page to place it, then drag and resize. The signature is stamped into the page when you save.',
    limits: ['This is a visual signature, like signing a printout. It is not a certificate-based digital signature, so it does not prove who signed.', 'Password-protected PDFs must be unlocked first.'],
    related: ['pdf/protect', 'pdf/organize', 'pdf/page-numbers'],
  },
  {
    slug: 'page-numbers', category: 'pdf', name: 'Add page numbers', kind: 'file', group: 'mark-up',
    blurb: 'Number every page, in the style you need.',
    description: 'Add page numbers to a PDF in your browser. Choose the position, style and starting number, and skip the cover page. No upload.',
    keywords: ['page numbers', 'number pages', 'paginate', 'pagination', 'footer', 'bates'],
    accept: 'application/pdf,.pdf',
    options: [
      { kind: 'select', key: 'position', label: 'Position', default: 'bottom-center', choices: [
        { value: 'bottom-center', label: 'Bottom centre' }, { value: 'bottom-right', label: 'Bottom right' }, { value: 'bottom-left', label: 'Bottom left' },
        { value: 'top-center', label: 'Top centre' }, { value: 'top-right', label: 'Top right' }, { value: 'top-left', label: 'Top left' },
      ] },
      { kind: 'select', key: 'style', label: 'Style', default: 'n', choices: [
        { value: 'n', label: '1' }, { value: 'n-of-total', label: '1 / 10' },
        { value: 'page-n', label: 'Page 1' }, { value: 'page-n-of-total', label: 'Page 1 of 10' },
      ] },
      { kind: 'number', key: 'start', label: 'Start at', min: 1, max: 9999, step: 1, default: 1 },
      { kind: 'range', key: 'size', label: 'Size', min: 8, max: 24, step: 1, default: 11, suffix: 'pt' },
      { kind: 'toggle', key: 'skipFirst', label: 'Skip the first page', default: false, help: 'For a cover page. Numbering starts on page 2.' },
    ],
    about: 'Numbers are drawn 10 mm in from the edge of each page as it is displayed, so pages that were scanned sideways still get their number upright in the right corner.',
    limits: ['Latin digits and text only, in Helvetica.', 'Numbers are drawn on top of the page. If the page already has content in that corner, they will overlap it.'],
    related: ['pdf/organize', 'pdf/watermark', 'pdf/merge'],
  },
  {
    slug: 'compress', category: 'pdf', name: 'Compress PDF', kind: 'file', group: 'shrink',
    blurb: 'Shrink a PDF, or get it under an exact size.',
    description: 'Compress a PDF in your browser, or get it under an exact limit like 500 KB for an upload portal. No upload, no account.',
    keywords: ['compress', 'reduce', 'shrink', 'optimise', 'optimize', 'smaller', 'pdf', 'kb', 'under 500kb', 'under 1mb', 'file size limit', 'upload limit'],
    accept: 'application/pdf,.pdf',
    options: [
      { kind: 'select', key: 'target', label: 'Target size', default: '0', choices: [
        { value: '0', label: 'None, choose a mode' },
        { value: '100', label: 'Under 100 KB' }, { value: '200', label: 'Under 200 KB' },
        { value: '500', label: 'Under 500 KB' }, { value: '1000', label: 'Under 1 MB' },
        { value: '2000', label: 'Under 2 MB' }, { value: '5000', label: 'Under 5 MB' },
      ], help: 'For upload portals with a size limit. Tries lossless first, so text stays selectable whenever that is enough.' },
      { kind: 'select', key: 'mode', label: 'Mode', default: 'lossless', when: { key: 'target', equals: '0' }, choices: [
        { value: 'lossless', label: 'Lossless (keeps text selectable)' },
        { value: 'strong', label: 'Strong (rasterises pages)' },
      ], help: 'Strong re-encodes each page as an image. Much smaller, but text stops being selectable or searchable.' },
      { kind: 'range', key: 'quality', label: 'Image quality', min: 30, max: 95, step: 5, default: 70, suffix: '%', when: [{ key: 'target', equals: '0' }, { key: 'mode', equals: 'strong' }], help: 'Strong mode only.' },
    ],
    about: 'With a target size, the file is first repacked losslessly; if that lands under the limit, text stays selectable. Otherwise each page is re-encoded as an image at the highest quality and resolution that still fits. Without a target, Lossless mode repacks the file structure (a small saving) and Strong mode rasterises every page (a large one).',
    limits: ['Reaching a small target usually means rasterising pages, so text stops being selectable and searchable.', 'Pages are never rendered below about 45 dpi. If a document cannot fit and stay readable, the tool says so instead of handing back an unreadable file. Splitting it first usually helps.', 'Lossless mode often saves only a few percent. That is the honest ceiling for structural compression.'],
    related: ['pdf/split', 'image/compress', 'pdf/merge'],
    variants: [
      { slug: '100kb', short: '100 KB', name: 'Compress PDF to 100 KB', blurb: 'Get a PDF under 100 KB.', defaults: { target: '100' },
        description: 'Compress a PDF to under 100 KB in your browser, for portals with a strict upload limit. No upload, no account, no watermark.' },
      { slug: '200kb', short: '200 KB', name: 'Compress PDF to 200 KB', blurb: 'Get a PDF under 200 KB.', defaults: { target: '200' },
        description: 'Compress a PDF to under 200 KB in your browser, for forms and portals with an upload limit. No upload, no account, no watermark.' },
      { slug: '500kb', short: '500 KB', name: 'Compress PDF to 500 KB', blurb: 'Get a PDF under 500 KB.', defaults: { target: '500' },
        description: 'Compress a PDF to under 500 KB in your browser, the limit many application portals use. No upload, no account, no watermark.' },
      { slug: '1mb', short: '1 MB', name: 'Compress PDF to 1 MB', blurb: 'Get a PDF under 1 MB.', defaults: { target: '1000' },
        description: 'Compress a PDF to under 1 MB in your browser, usually with text still selectable. No upload, no account, no watermark.' },
      { slug: '2mb', short: '2 MB', name: 'Compress PDF to 2 MB', blurb: 'Get a PDF under 2 MB.', defaults: { target: '2000' },
        description: 'Compress a PDF to under 2 MB in your browser for email and upload portals. No upload, no account, no watermark.' },
    ],
  },
  {
    slug: 'protect', category: 'pdf', name: 'Protect PDF', kind: 'file', group: 'secure', heavy: true,
    blurb: 'Lock a PDF with a password.',
    description: 'Password-protect a PDF with AES-256 encryption in your browser, and optionally block printing or copying. The password never leaves your device.',
    keywords: ['protect', 'password', 'encrypt', 'lock', 'secure', 'aes', 'kata laluan'],
    accept: 'application/pdf,.pdf',
    options: [
      { kind: 'text', key: 'password', label: 'Password', default: '', secret: true, help: 'Needed to open the file. There is no way to recover it if forgotten.' },
      { kind: 'toggle', key: 'allowPrint', label: 'Allow printing', default: true },
      { kind: 'toggle', key: 'allowCopy', label: 'Allow copying text', default: true },
      { kind: 'toggle', key: 'allowEdit', label: 'Allow editing', default: false },
    ],
    about: 'Encrypts the whole file with AES-256 using qpdf, the standard open-source PDF tool, compiled to run in your browser. The password is used on this page and nowhere else.',
    limits: ['A forgotten password cannot be recovered, by us or anyone. Keep it somewhere safe.', 'Print and copy restrictions are honoured by mainstream PDF readers, but they are requests, not guarantees: some tools ignore them.', 'The encryption engine (about 1.3 MB) downloads from this site the first time it runs.'],
    related: ['pdf/unlock', 'pdf/sign', 'pdf/watermark'],
  },
  {
    slug: 'unlock', category: 'pdf', name: 'Unlock PDF', kind: 'file', group: 'secure', heavy: true,
    blurb: 'Remove a password you know.',
    description: 'Remove the password and restrictions from a PDF in your browser, using the password you already have. Nothing is uploaded.',
    keywords: ['unlock', 'remove password', 'decrypt', 'unprotect', 'open locked pdf', 'restrictions'],
    accept: 'application/pdf,.pdf',
    options: [
      { kind: 'text', key: 'password', label: 'Password', default: '', secret: true, help: 'Leave empty if the file opens without one and you only want to lift its restrictions.' },
    ],
    about: 'Decrypts the file with qpdf, compiled to run in your browser, and saves a copy with no password and no restrictions.',
    limits: ['This does not crack passwords. You need the password that opens the file.', 'Only unlock files you have the right to use.'],
    related: ['pdf/protect', 'pdf/compress', 'pdf/merge'],
  },

  // ─── Media ────────────────────────────────────────────────────────────────
  {
    slug: 'compress-video', category: 'media', name: 'Compress video', kind: 'file', heavy: true,
    blurb: 'Hit a target file size, in your browser.',
    description: 'Compress video to a target size in your browser using ffmpeg.wasm. No upload, no size cap, no account.',
    keywords: ['compress video', 'shrink', 'reduce', 'mp4', 'target size', 'discord', 'smaller', 'bitrate'],
    accept: 'video/*',
    options: [
      { kind: 'number', key: 'targetMB', label: 'Target size', min: 1, max: 2000, step: 1, default: 15, suffix: 'MB', help: 'The encoder aims for this. Expect to land within a few percent.' },
      { kind: 'select', key: 'audio', label: 'Audio', default: '128', choices: [
        { value: '128', label: '128 kbps, the default' }, { value: '96', label: '96 kbps' }, { value: '64', label: '64 kbps, smaller file' }, { value: 'none', label: 'Remove audio' },
      ] },
    ],
    about: 'Computes the bitrate needed to land on your target size given the video length, then re-encodes at that bitrate. Audio is re-encoded to a known bitrate so the size arithmetic is actually correct.',
    limits: ['Runs at roughly real-time or slower. A 5 minute video takes minutes, not seconds.', 'Single-pass encoding, so the final size lands close to the target but rarely exactly on it.', 'Needs a desktop browser for anything large; mobile memory is the binding constraint.'],
    related: ['media/extract-audio', 'media/transcribe', 'image/compress'],
  },
  {
    slug: 'extract-audio', category: 'media', name: 'Extract audio', kind: 'file', heavy: true,
    blurb: 'Pull the audio track out of a video as MP3.',
    description: 'Extract audio from video to MP3 in your browser. No upload and no length limit.',
    keywords: ['extract audio', 'video to mp3', 'rip audio', 'soundtrack', 'strip', 'convert', 'mp3'],
    accept: 'video/*',
    options: [{ kind: 'select', key: 'bitrate', label: 'Quality', default: '192', choices: [
      { value: '320', label: '320 kbps' }, { value: '192', label: '192 kbps, the default' }, { value: '128', label: '128 kbps' },
    ] }],
    about: 'Discards the video stream and re-encodes the audio to MP3.',
    limits: ['Re-encoding to MP3 is lossy. The source audio is already compressed, so this is a second generation.'],
    related: ['media/transcribe', 'media/compress-video'],
  },
  {
    slug: 'transcribe', category: 'media', name: 'Audio to text', kind: 'file', heavy: true,
    seoTitle: 'Audio to text online, English and Malay, free, no upload | Nhako Tools',
    blurb: 'Transcribe English or Malay speech, on your device.',
    description: 'Transcribe audio and video to text in your browser with Whisper, in English, Malay and other languages. The model runs on your device, so nothing is uploaded.',
    keywords: ['transcribe', 'transcription', 'speech to text', 'audio to text', 'whisper', 'subtitles', 'captions', 'dictation', 'stt', 'malay', 'bahasa melayu', 'transkripsi'],
    accept: 'audio/*,video/*',
    options: [
      { kind: 'select', key: 'language', label: 'Language', default: 'en', choices: [
        { value: 'en', label: 'English' }, { value: 'ms', label: 'Malay' }, { value: 'auto', label: 'Detect (other languages)' },
      ] },
      { kind: 'select', key: 'quality', label: 'Model', default: 'fast', choices: [
        { value: 'fast', label: 'Fast, smaller download' }, { value: 'accurate', label: 'Accurate, larger download' },
      ], help: 'English: 41 MB or 77 MB. Malay and other languages: 77 MB or 250 MB. Each is downloaded once.' },
    ],
    about: 'Runs OpenAI Whisper on your device through WebAssembly. English uses the English-only models; Malay and other languages use the multilingual ones. The model is downloaded once and cached by your browser for every later run. The transcript is shown ready to copy, and saved as a .txt.',
    limits: ['Whisper is weaker in Malay than in English. On 12 clearly read Malay sentences from Google\'s FLEURS set, Fast got about 4 words in 10 wrong and Accurate about 1 in 4. Use Accurate for Malay, and check the result.', 'The first run of each model downloads its weights once, from 41 MB to 250 MB. After that it works offline.', 'Accuracy is well below the full-size cloud models, especially with accents, several speakers, mixed languages or background noise.', 'Long recordings are slow: expect a sizeable fraction of the audio length, and much more with the Accurate model.'],
    related: ['media/extract-audio', 'dev/word-count', 'pdf/to-text'],
  },
  {
    slug: 'teleprompter', category: 'media', name: 'Teleprompter', kind: 'app',
    seoTitle: 'Teleprompter online with camera recording, free, no upload | Nhako Tools',
    blurb: 'Read a script on a tablet, and record yourself.',
    description: 'Free online teleprompter for tablets: set the words-per-minute speed, mirror for a rig, control it by pedal or phone, and record yourself. No upload.',
    keywords: ['teleprompter', 'prompter', 'autocue', 'script', 'speech', 'presentation', 'record video', 'ipad teleprompter', 'tablet', 'mirror', 'beam splitter', 'foot pedal', 'remote', 'voice scroll', 'vlog', 'youtube'],
    about: 'Type or import a script, then read it full screen at a steady words-per-minute pace, with the reading line high on the screen so your eyes stay near the camera. Add sections to jump between, [PAUSE] cues that stop the scroll, and highlights. Control it with taps, a keyboard, a Bluetooth page turner or foot pedal, or your phone. Record camera and microphone while you read; takes are saved on this device.',
    limits: [
      'Recordings are saved in this browser\'s storage on this device. Clearing site data deletes them, so download the takes you want to keep.',
      'The phone remote needs both devices online. It passes only button presses through a relay run by Supabase, never your script, video or audio.',
      'Voice-follow uses your browser\'s speech recognition, which in Chrome and Edge sends your voice to Google while it listens. It is off unless you turn it on.',
      'Long takes have not yet been tested on every tablet. Try a short take first on a new device.',
    ],
    related: ['media/compress-video', 'media/transcribe', 'dev/word-count'],
  },

  // ─── Image ────────────────────────────────────────────────────────────────
  {
    slug: 'compress', category: 'image', name: 'Compress image', kind: 'file', group: 'shrink',
    blurb: 'Shrink JPG, PNG and WebP, or hit an exact size.',
    description: 'Compress images in your browser, or get them under an exact limit like 100 KB for a form. Adjust quality and watch the size change. No upload.',
    keywords: ['compress image', 'shrink', 'reduce', 'optimise', 'optimize', 'jpg', 'png', 'webp', 'smaller', 'tinypng', 'kb', 'under 100kb', 'photo size', 'upload limit'],
    accept: 'image/*', multiple: true,
    options: [
      { kind: 'select', key: 'target', label: 'Target size', default: '0', choices: [
        { value: '0', label: 'None, choose a quality' },
        { value: '20', label: 'Under 20 KB' }, { value: '50', label: 'Under 50 KB' },
        { value: '100', label: 'Under 100 KB' }, { value: '200', label: 'Under 200 KB' },
        { value: '500', label: 'Under 500 KB' }, { value: '1000', label: 'Under 1 MB' },
        { value: '2000', label: 'Under 2 MB' },
      ], help: 'For forms and portals with a size limit. Lowers quality first and only shrinks the dimensions if it has to.' },
      { kind: 'range', key: 'quality', label: 'Quality', min: 30, max: 95, step: 5, default: 75, suffix: '%', when: { key: 'target', equals: '0' }, help: 'Has no effect on PNG, which is lossless.' },
      { kind: 'select', key: 'format', label: 'Output', default: 'auto', choices: [
        { value: 'auto', label: 'Keep original format' }, { value: 'webp', label: 'WebP, usually the smallest' }, { value: 'jpeg', label: 'JPG' },
      ], help: 'Most portals only accept JPG. With a target size, PNG becomes JPG.' },
    ],
    about: 'Decodes each image and re-encodes it. With a target size, it searches for the highest quality that lands under the limit, and only reduces the pixel dimensions when even low quality is too big. The size is aimed at 1,000 bytes per KB, so the file passes whichever way a portal counts.',
    limits: ['Re-encoding is lossy. Compressing an already-compressed image degrades it further.', 'PNG is lossless, so keeping PNG rarely saves anything. Choose WebP, or a target size, to actually shrink a PNG.', 'Without a target, a re-encode that would be larger returns the original unchanged.', 'Transparency is kept in PNG and WebP. JPG has none, so transparent areas become white.'],
    related: ['image/passport-photo', 'image/resize', 'pdf/compress'],
    variants: [
      { slug: '20kb', short: '20 KB', name: 'Compress image to 20 KB', blurb: 'Get a photo under 20 KB.', defaults: { target: '20', format: 'jpeg' },
        description: 'Compress a JPG or photo to under 20 KB in your browser, for signature and photo uploads with a tiny limit. No upload, no account.' },
      { slug: '50kb', short: '50 KB', name: 'Compress image to 50 KB', blurb: 'Get a photo under 50 KB.', defaults: { target: '50', format: 'jpeg' },
        description: 'Compress a JPG or photo to under 50 KB in your browser, for online forms with a strict limit. No upload, no account.' },
      { slug: '100kb', short: '100 KB', name: 'Compress image to 100 KB', blurb: 'Get a photo under 100 KB.', defaults: { target: '100', format: 'jpeg' },
        description: 'Compress a JPG or photo to under 100 KB in your browser, the limit many application forms use. No upload, no account.' },
      { slug: '200kb', short: '200 KB', name: 'Compress image to 200 KB', blurb: 'Get a photo under 200 KB.', defaults: { target: '200', format: 'jpeg' },
        description: 'Compress a JPG or photo to under 200 KB in your browser for forms and portals. No upload, no account, no watermark.' },
      { slug: '500kb', short: '500 KB', name: 'Compress image to 500 KB', blurb: 'Get a photo under 500 KB.', defaults: { target: '500', format: 'jpeg' },
        description: 'Compress a JPG or photo to under 500 KB in your browser, keeping it sharp. No upload, no account, no watermark.' },
      { slug: '1mb', short: '1 MB', name: 'Compress image to 1 MB', blurb: 'Get a photo under 1 MB.', defaults: { target: '1000', format: 'jpeg' },
        description: 'Compress a JPG or photo to under 1 MB in your browser without visible loss. No upload, no account, no watermark.' },
      { slug: 'spa-myresume', short: 'SPA MyResume', name: 'Photo and documents for SPA MyRésumé', blurb: 'JPG under 1 MB, as SPA requires.', defaults: { target: '1000', format: 'jpeg' },
        description: 'Get photos and scanned documents under the 1 MB SPA MyRésumé limit, in your browser. JPG output, no upload, no account.',
        about: 'SPA\'s MyRésumé guide (PANDUAN_GAMBAR.pdf, checked 18 September 2026) asks for photos and documents in .jpg or .png, each under 1 MB, and a profile photo of 35 mm × 50 mm on a white background. This preset produces JPG under 1 MB. For the profile photo itself, the passport photo maker has an SPA preset.' },
    ],
  },
  {
    slug: 'convert', category: 'image', name: 'Convert image', kind: 'file', group: 'convert',
    blurb: 'Move between JPG, PNG, WebP and AVIF.',
    description: 'Convert images between JPG, PNG, WebP and AVIF in your browser. Batch conversion with no upload.',
    keywords: ['convert image', 'jpg to png', 'png to jpg', 'webp', 'avif', 'heic', 'format', 'change'],
    accept: 'image/*', multiple: true,
    options: [
      { kind: 'select', key: 'format', label: 'Convert to', default: 'webp', choices: [
        { value: 'webp', label: 'WebP' }, { value: 'jpeg', label: 'JPG' }, { value: 'png', label: 'PNG' }, { value: 'avif', label: 'AVIF' },
      ] },
      { kind: 'range', key: 'quality', label: 'Quality', min: 30, max: 100, step: 5, default: 85, suffix: '%', help: 'Ignored for PNG, which is lossless.' },
    ],
    about: 'Decodes with the browser image pipeline and re-encodes to the chosen format.',
    limits: ['AVIF encoding depends on browser support and is slower than the others.', 'Converting to PNG from a lossy source will usually make the file larger, not smaller.'],
    related: ['image/compress', 'image/resize', 'pdf/to-image'],
  },
  {
    slug: 'resize', category: 'image', name: 'Resize image', kind: 'file', group: 'transform',
    blurb: 'Scale images to exact dimensions.',
    description: 'Resize images in your browser. Set a width or height, keep the aspect ratio, and batch process without uploading.',
    keywords: ['resize', 'scale', 'dimensions', 'width', 'height', 'thumbnail', 'crop', 'shrink', 'enlarge'],
    accept: 'image/*', multiple: true,
    options: [
      { kind: 'number', key: 'width', label: 'Width', min: 0, max: 20000, step: 1, default: 1280, suffix: 'px', help: '0 to derive from height.' },
      { kind: 'number', key: 'height', label: 'Height', min: 0, max: 20000, step: 1, default: 0, suffix: 'px', help: '0 to derive from width.' },
      { kind: 'toggle', key: 'noUpscale', label: 'Never enlarge', default: true, help: 'Leave images already smaller than the target untouched.' },
    ],
    about: 'Scales with the browser’s high-quality resampling. Setting only one dimension preserves the aspect ratio.',
    limits: ['Enlarging cannot invent detail. This is plain resampling, not AI upscaling.'],
    related: ['image/compress', 'image/convert'],
  },

  {
    slug: 'crop', category: 'image', name: 'Crop image', kind: 'app', group: 'transform',
    blurb: 'Cut an image to a shape or ratio.',
    description: 'Crop images in your browser: drag the frame, pick a ratio like 1:1 or 16:9, and save in the original format. No upload, no watermark.',
    keywords: ['crop', 'cut', 'trim', 'square', 'aspect ratio', '1:1', '16:9', 'profile picture', 'thumbnail'],
    accept: 'image/*',
    about: 'Drag the frame or its handles, or pick a fixed ratio. The exact pixel size is shown as you go, and the crop is saved in the image\'s own format.',
    limits: ['One image at a time.', 'JPG and WebP are re-encoded at high quality when saved; PNG stays lossless.'],
    related: ['image/resize', 'image/rotate', 'image/passport-photo'],
  },
  {
    slug: 'rotate', category: 'image', name: 'Rotate image', kind: 'file', group: 'transform',
    blurb: 'Turn or flip images.',
    description: 'Rotate images 90 or 180 degrees, or flip them, in your browser. Batch several at once. No upload, no account.',
    keywords: ['rotate', 'turn', 'flip', 'mirror', 'sideways', 'upside down', 'orientation'],
    accept: 'image/*', multiple: true,
    options: [
      { kind: 'select', key: 'action', label: 'Action', default: 'cw', choices: [
        { value: 'cw', label: 'Rotate 90° clockwise' }, { value: 'ccw', label: 'Rotate 90° anticlockwise' }, { value: '180', label: 'Rotate 180°' },
        { value: 'flip-h', label: 'Flip horizontally' }, { value: 'flip-v', label: 'Flip vertically' },
      ] },
    ],
    about: 'Redraws each image turned or mirrored and saves it in its own format.',
    limits: ['JPG and WebP are re-encoded at high quality, a small loss each time. PNG stays lossless.'],
    related: ['image/crop', 'image/resize', 'pdf/rotate'],
  },
  {
    slug: 'watermark', category: 'image', name: 'Watermark image', kind: 'file', group: 'edit', stageFirst: true,
    blurb: 'Stamp text across photos.',
    description: 'Add a text watermark to images in your browser: tiled, centred or in a corner, with your own opacity. Batch several at once. No upload.',
    keywords: ['watermark', 'stamp', 'copyright', 'protect photo', 'text on image', 'tera air'],
    accept: 'image/*', multiple: true,
    options: [
      { kind: 'text', key: 'text', label: 'Text', default: '', placeholder: '© Your name' },
      { kind: 'select', key: 'position', label: 'Position', default: 'tile', choices: [
        { value: 'tile', label: 'Tiled across the image' }, { value: 'center', label: 'Centre' },
        { value: 'bottom-right', label: 'Bottom right' }, { value: 'bottom-left', label: 'Bottom left' },
        { value: 'top-right', label: 'Top right' }, { value: 'top-left', label: 'Top left' },
      ] },
      { kind: 'range', key: 'size', label: 'Size', min: 2, max: 20, step: 1, default: 6, suffix: '%' },
      { kind: 'range', key: 'opacity', label: 'Opacity', min: 5, max: 100, step: 5, default: 35, suffix: '%' },
      { kind: 'select', key: 'color', label: 'Colour', default: 'white', choices: [
        { value: 'white', label: 'White' }, { value: 'black', label: 'Black' }, { value: 'red', label: 'Red' },
      ] },
    ],
    about: 'Draws the text onto every image with a faint outline, so it stays readable on light and dark areas alike. Tiling makes it hard to crop out.',
    limits: ['A watermark discourages reuse; it cannot prevent it. Anyone determined can paint it out.', 'JPG and WebP are re-encoded at high quality.'],
    related: ['pdf/watermark', 'image/compress', 'image/remove-metadata'],
  },
  {
    slug: 'heic-to-jpg', category: 'image', name: 'HEIC to JPG', kind: 'file', group: 'convert', heavy: true,
    blurb: 'Convert iPhone photos to JPG.',
    description: 'Convert iPhone HEIC photos to JPG or PNG in your browser, in batches. For forms and portals that reject HEIC. No upload, no account.',
    keywords: ['heic', 'heif', 'heic to jpg', 'iphone photo', 'convert heic', 'apple photo', 'heic to png'],
    accept: '.heic,.heif,image/heic,image/heif', multiple: true,
    options: [
      { kind: 'select', key: 'format', label: 'Convert to', default: 'jpeg', choices: [
        { value: 'jpeg', label: 'JPG' }, { value: 'png', label: 'PNG' },
      ] },
      { kind: 'range', key: 'quality', label: 'Quality', min: 50, max: 100, step: 5, default: 92, suffix: '%', when: { key: 'format', equals: 'jpeg' } },
    ],
    about: 'Safari decodes HEIC itself. Other browsers get libheif, the reference open-source HEIC decoder, compiled to run on your device and downloaded (about 1.4 MB) only the first time it is needed.',
    limits: ['Live Photo motion and depth data are not kept, only the still image.', 'Multi-image HEIC files (bursts) convert only their main image.'],
    related: ['image/compress', 'pdf/jpg-to-pdf', 'image/remove-metadata'],
  },
  {
    slug: 'remove-metadata', category: 'image', name: 'Remove photo metadata', kind: 'file', group: 'clean',
    blurb: 'Strip GPS location and camera details.',
    description: 'Remove EXIF data from photos in your browser: GPS location, camera, date and more, without touching the image itself. No upload.',
    keywords: ['exif', 'metadata', 'remove exif', 'gps', 'location', 'strip', 'privacy', 'geotag', 'clean'],
    accept: 'image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp', multiple: true,
    about: 'Removes EXIF, XMP, IPTC and comment data by editing the file\'s structure, so the picture itself is byte-for-byte unchanged. It tells you what it found first, including any GPS location, which is often a home address. Colour profiles and the rotation flag are kept, so the photo still looks and faces the same.',
    limits: ['JPG, PNG and WebP only. Convert HEIC to JPG first.', 'The image pixels are untouched, so anything visible in the picture (a street sign, a face) is still there.'],
    related: ['image/heic-to-jpg', 'image/compress', 'image/watermark'],
  },
  {
    slug: 'ocr', category: 'image', name: 'Image to text (OCR)', kind: 'file', group: 'clean', heavy: true, multiple: true,
    seoTitle: 'Image to text (OCR) online, English and Malay, free | Nhako Tools',
    blurb: 'Pull the text out of photos and screenshots.',
    description: 'Copy text from photos, screenshots and scans in your browser with OCR, in English or Malay. Get plain text or a searchable PDF. No upload.',
    keywords: ['ocr', 'image to text', 'photo to text', 'picture to text', 'extract text', 'screenshot to text', 'text recognition', 'scan to text', 'gambar ke teks'],
    accept: 'image/*',
    options: [
      { kind: 'select', key: 'language', label: 'Language', default: 'eng+msa', choices: [
        { value: 'eng+msa', label: 'English and Malay' }, { value: 'eng', label: 'English' }, { value: 'msa', label: 'Malay' },
      ], help: 'Choosing only the language on the page is a little faster and more accurate.' },
      { kind: 'select', key: 'output', label: 'Save as', default: 'text', choices: [
        { value: 'text', label: 'Text (.txt)' }, { value: 'pdf', label: 'Searchable PDF' },
      ] },
    ],
    about: 'Tesseract, the open-source OCR engine, runs in your browser and reads each image in English, Malay or both. Phone photos are turned upright first and small screenshots enlarged, both of which help it. You get the text to copy, and can save it as a .txt or as a PDF of the images with the text searchable.',
    limits: ['The first run downloads the OCR engine and language data once, about 15 MB, from this site.', 'Printed text only. Handwriting is read poorly or not at all.', 'Straight, sharp, well-lit photos read far better than skewed or blurred ones.', 'Layout is not kept: columns and tables come out as plain lines of text.'],
    related: ['pdf/ocr', 'image/compress', 'dev/word-count'],
  },
  {
    slug: 'remove-background', category: 'image', name: 'Remove background', kind: 'file', group: 'edit', heavy: true, multiple: true,
    seoTitle: 'Remove background from image online, free, no upload | Nhako Tools',
    blurb: 'Cut out the subject, on your device.',
    description: 'Remove the background from a photo in your browser: get a transparent PNG, or the subject on white. The AI model runs on your device, so nothing is uploaded.',
    keywords: ['remove background', 'background remover', 'remove bg', 'transparent background', 'cut out', 'erase background', 'product photo', 'png', 'buang latar belakang'],
    accept: 'image/jpeg,image/png,image/webp',
    options: [
      { kind: 'select', key: 'subject', label: 'Subject', default: 'general', choices: [
        { value: 'general', label: 'Objects and products' }, { value: 'person', label: 'People and animals' },
      ], help: 'Two different models, each downloaded once when first used. If one leaves pieces behind, try the other.' },
      { kind: 'select', key: 'background', label: 'Background', default: 'transparent', choices: [
        { value: 'transparent', label: 'Transparent (PNG)' }, { value: 'white', label: 'White (JPG)' }, { value: 'black', label: 'Black (JPG)' },
      ] },
    ],
    about: 'A segmentation model finds the main subject, and everything else is made transparent or filled with white or black. There are two openly licensed models: ISNet (Apache-2.0), trained on everyday objects, for products and things; and ormbg (Apache-2.0), trained on people, which also does well on animals. Both run in your browser through WebAssembly, so the photo never leaves your device.',
    limits: ['The first run of each model downloads it once, about 45 MB, from Hugging Face: a download of the model, never an upload of your photo.', 'Neither model is perfect. The object model can leave specks on grass or gravel; the people model can drop parts of large objects. Check the result, and try the other model if needed.', 'It keeps the most prominent subject. Busy scenes, like a full shelf, can come out partly cut.', 'Each photo takes about 10 seconds on a laptop, longer on phones.'],
    related: ['image/passport-photo', 'image/crop', 'image/compress'],
  },
  {
    slug: 'passport-photo', category: 'image', name: 'Passport photo maker', kind: 'app', group: 'create',
    seoTitle: 'Passport photo maker 35×50 mm, white background | Nhako Tools',
    blurb: 'Crop a 35×50 mm photo, white background, print sheet.',
    description: 'Make a 35×50 mm passport or application photo in your browser: crop, white background, a digital file and a 4R print sheet. No upload.',
    keywords: ['passport photo', 'gambar pasport', 'photo 35x50', '35 x 50', 'white background', 'id photo', 'spa photo', 'print sheet', '4r', 'visa photo'],
    accept: 'image/jpeg,image/png,image/webp',
    about: 'Drop a photo, line your face up with the guide, and save both a digital JPG and a 4R (4×6 inch) sheet ready for any photo shop to print. The background can be replaced with plain white by a small segmentation model that runs on your device.',
    limits: ['The Malaysian Immigration Department takes adult passport photos at the counter. It asks for a printed 35×50 mm photo on white only for children under 4.', 'Background replacement works best with a clear outline against a plain wall. Fine hair edges may need a second try with better light.', 'This checks size and framing, not whether an office will accept your expression, lighting or glasses. Each office has the final say.'],
    related: ['image/compress', 'image/resize', 'pdf/compress'],
  },

  // ─── Calculators ──────────────────────────────────────────────────────────
  {
    slug: 'take-home-pay', category: 'calc', name: 'Salary calculator (Malaysia)', kind: 'app',
    seoTitle: 'Malaysia salary calculator 2026: EPF, SOCSO, EIS, PCB | Nhako Tools',
    blurb: 'Net pay after EPF, SOCSO, EIS and PCB.',
    description: 'Work out your 2026 take-home pay in Malaysia: EPF, SOCSO with LINDUNG 24 Jam, EIS and PCB tax, from the official tables. Free, no sign-up.',
    keywords: ['salary', 'gaji', 'take home', 'net pay', 'epf', 'kwsp', 'socso', 'perkeso', 'eis', 'sip', 'pcb', 'mtd', 'income tax', 'cukai', 'payslip'],
    about: 'Enter a monthly salary and your household, and get every statutory deduction with the employer\'s share alongside. EPF comes from the Third Schedule, SOCSO and EIS from PERKESO\'s tables, and PCB from LHDN\'s published formula, checked against LHDN\'s own worked example to the sen.',
    limits: ['For Malaysian citizens and permanent residents below 60 on a steady monthly salary. Different EPF and SOCSO rates apply from 60, and to foreign workers.', 'PCB is the regular monthly amount for a salary that stays the same all year. A bonus, a mid-year start or TP1 deductions change it, and your employer\'s payroll has the final figure.', 'PCB is a deduction toward your income tax, not the final bill. Your e-Filing return settles the year.'],
    related: ['image/passport-photo', 'pdf/compress', 'image/compress'],
  },

  // ─── Developer ────────────────────────────────────────────────────────────
  {
    slug: 'json', category: 'dev', name: 'JSON formatter', kind: 'text', group: 'text',
    blurb: 'Format, validate and minify JSON.',
    description: 'Format and validate JSON in your browser with syntax highlighting. Pinpoints the exact line of a syntax error.',
    keywords: ['json', 'format', 'pretty print', 'beautify', 'validate', 'minify', 'lint', 'parse', 'prettify'],
    options: [
      { kind: 'select', key: 'indent', label: 'Indent', default: '2', choices: [
        { value: '2', label: '2 spaces' }, { value: '4', label: '4 spaces' }, { value: 'tab', label: 'Tabs' }, { value: '0', label: 'Minify' },
      ] },
      { kind: 'toggle', key: 'sortKeys', label: 'Sort keys', default: false },
    ],
    about: 'Parses with the browser’s own JSON parser, so what validates here is exactly what validates in your code. Errors report the line and column.',
    limits: ['Strict JSON only. No comments, no trailing commas, no single quotes.'],
    related: ['dev/jwt', 'dev/base64', 'dev/diff'],
  },
  {
    slug: 'jwt', category: 'dev', name: 'JWT decoder', kind: 'text', group: 'encode',
    blurb: 'Decode a token’s header and payload.',
    description: 'Decode JSON Web Tokens in your browser. The token is never sent anywhere, which matters, because tokens are credentials.',
    keywords: ['jwt', 'json web token', 'decode', 'token', 'bearer', 'auth', 'claims', 'jwt.io'],
    about: 'Splits the token, base64url-decodes the header and payload, and renders the claims. Timestamp claims (`exp`, `iat`, `nbf`) are shown as readable dates alongside their raw values.',
    limits: ['Decoding only. The signature is not verified, and a decoded token is not a trusted token.', 'Never paste a production token into a tool that uploads it. This one does not, and you can confirm that in your network tab.'],
    related: ['dev/base64', 'dev/json', 'dev/hash'],
  },
  {
    slug: 'base64', category: 'dev', name: 'Base64 converter', kind: 'text', group: 'encode',
    blurb: 'Encode and decode Base64.',
    description: 'Encode and decode Base64 in your browser, with full Unicode support and URL-safe output.',
    keywords: ['base64', 'encode', 'decode', 'btoa', 'atob', 'b64', 'data uri', 'url safe'],
    options: [
      { kind: 'select', key: 'mode', label: 'Mode', default: 'encode', choices: [{ value: 'encode', label: 'Encode' }, { value: 'decode', label: 'Decode' }] },
      { kind: 'toggle', key: 'urlSafe', label: 'URL-safe alphabet', default: false, help: 'Uses - and _ instead of + and /, and drops padding.' },
    ],
    about: 'Handles multi-byte UTF-8 correctly in both directions, so emoji and non-Latin scripts round-trip exactly.',
    limits: ['Text only. For files, use the file tools.'],
    related: ['dev/jwt', 'dev/hash', 'dev/json'],
  },
  {
    slug: 'word-count', category: 'dev', name: 'Word counter', kind: 'text', group: 'text',
    blurb: 'Live word, character and reading-time counts.',
    description: 'Count words, characters, sentences and reading time as you type. Nothing is sent anywhere.',
    keywords: ['word count', 'character count', 'letter count', 'reading time', 'essay', 'twitter', 'limit', 'counter'],
    about: 'Counts update on every keystroke. Reading time assumes 200 words per minute, speaking time 130.',
    limits: ['Word counting splits on whitespace, which undercounts languages that do not use spaces between words.'],
    related: ['dev/diff', 'pdf/to-text', 'media/transcribe'],
  },
  {
    slug: 'hash', category: 'dev', name: 'Hash generator', kind: 'text', group: 'encode',
    blurb: 'SHA-1, SHA-256, SHA-384 and SHA-512.',
    description: 'Generate SHA hashes in your browser using the native Web Crypto API. Nothing is uploaded.',
    keywords: ['hash', 'sha', 'sha256', 'sha1', 'sha512', 'checksum', 'digest', 'fingerprint', 'md5'],
    options: [{ kind: 'select', key: 'algo', label: 'Algorithm', default: 'SHA-256', choices: [
      { value: 'SHA-1', label: 'SHA-1' }, { value: 'SHA-256', label: 'SHA-256' }, { value: 'SHA-384', label: 'SHA-384' }, { value: 'SHA-512', label: 'SHA-512' },
    ] }],
    about: 'Uses the browser’s built-in Web Crypto implementation, the same primitive your runtime uses.',
    limits: ['MD5 is not offered. Web Crypto deliberately omits it because it is broken for anything security-related.', 'SHA-1 is included for checking legacy checksums only. Do not use it for security.'],
    related: ['dev/uuid', 'dev/base64', 'dev/jwt'],
  },
  {
    slug: 'uuid', category: 'dev', name: 'UUID generator', kind: 'text', group: 'generate', generator: true,
    blurb: 'Cryptographically random UUIDs.',
    description: 'Generate v4 UUIDs in your browser using the native crypto API. Bulk generation, no upload.',
    keywords: ['uuid', 'guid', 'v4', 'random', 'identifier', 'id', 'generate', 'unique'],
    options: [
      { kind: 'number', key: 'count', label: 'How many', min: 1, max: 1000, step: 1, default: 10 },
      { kind: 'toggle', key: 'uppercase', label: 'Uppercase', default: false },
      { kind: 'toggle', key: 'braces', label: 'Wrap in braces', default: false },
    ],
    about: 'Uses `crypto.randomUUID()`, which draws from the platform CSPRNG. These are suitable for real identifiers, not just placeholders.',
    limits: ['Version 4 only, which is random rather than time-ordered. If you need sortable ids, you want UUIDv7 or ULID.'],
    related: ['dev/hash', 'dev/qr'],
  },
  {
    slug: 'qr', category: 'dev', name: 'QR code generator', kind: 'text', group: 'generate', alsoIn: [{ category: 'image', group: 'create' }],
    blurb: 'Turn text or a URL into a QR code.',
    description: 'Generate a QR code in your browser and download it as PNG. No upload, no tracking redirect, no expiry.',
    keywords: ['qr', 'qr code', 'barcode', 'url', 'link', 'generate', 'scan', 'wifi'],
    options: [
      { kind: 'range', key: 'size', label: 'Size', min: 128, max: 1024, step: 64, default: 512, suffix: 'px' },
      { kind: 'select', key: 'ec', label: 'Error correction', default: 'M', choices: [
        { value: 'L', label: 'L (7%)' }, { value: 'M', label: 'M (15%)' }, { value: 'Q', label: 'Q (25%)' }, { value: 'H', label: 'H (30%)' },
      ], help: 'Higher survives more damage, at the cost of a denser code.' },
      { kind: 'toggle', key: 'margin', label: 'Quiet zone border', default: true },
    ],
    about: 'The QR code encodes your text directly. Many online generators encode a redirect through their own domain, so the code stops working when they do. This one does not.',
    limits: ['Around 2,900 characters at the lowest error correction, far fewer at the highest.'],
    related: ['dev/uuid', 'image/convert'],
  },
  {
    slug: 'diff', category: 'dev', name: 'Text diff', kind: 'text2', group: 'text',
    blurb: 'Compare two blocks of text.',
    description: 'Compare two texts and see exactly what changed, line by line or word by word. Runs entirely in your browser.',
    keywords: ['diff', 'compare', 'difference', 'changes', 'merge', 'text', 'file compare', 'delta'],
    options: [
      { kind: 'select', key: 'granularity', label: 'Compare by', default: 'line', choices: [
        { value: 'line', label: 'Line' }, { value: 'word', label: 'Word' }, { value: 'char', label: 'Character' },
      ] },
      { kind: 'toggle', key: 'ignoreWhitespace', label: 'Ignore whitespace', default: false },
    ],
    about: 'A standard diff over the two inputs, with additions and removals marked inline.',
    limits: ['Plain text only. No syntax awareness and no three-way merge.'],
    related: ['dev/json', 'dev/word-count'],
  },
  {
    slug: 'css-shadow', category: 'dev', name: 'CSS shadow generator', kind: 'text', group: 'generate', generator: true,
    blurb: 'Build box-shadows with a live preview.',
    description: 'Generate CSS box-shadow code with sliders and a live preview. Copy the result straight into your stylesheet.',
    keywords: ['css', 'box shadow', 'shadow', 'generator', 'drop shadow', 'elevation', 'design', 'style'],
    options: [
      { kind: 'range', key: 'x', label: 'Offset X', min: -50, max: 50, step: 1, default: 0, suffix: 'px' },
      { kind: 'range', key: 'y', label: 'Offset Y', min: -50, max: 50, step: 1, default: 8, suffix: 'px' },
      { kind: 'range', key: 'blur', label: 'Blur', min: 0, max: 100, step: 1, default: 24, suffix: 'px' },
      { kind: 'range', key: 'spread', label: 'Spread', min: -50, max: 50, step: 1, default: -6, suffix: 'px' },
      { kind: 'range', key: 'opacity', label: 'Opacity', min: 0, max: 100, step: 1, default: 18, suffix: '%' },
      { kind: 'text', key: 'color', label: 'Colour', default: '#131316', placeholder: '#131316' },
      { kind: 'toggle', key: 'inset', label: 'Inset', default: false },
    ],
    about: 'Emits a single `box-shadow` declaration. The preview swatch uses the exact value you would paste.',
    limits: ['One shadow layer. Stacked shadows are more convincing, but that is a different tool.'],
    related: ['dev/json', 'image/convert'],
  },
] as const;

export const TOOLS_BY_ID = new Map(TOOLS.map((t) => [`${t.category}/${t.slug}`, t]));

export const toolsIn = (category: string): ToolMeta[] => TOOLS.filter((t) => t.category === category);
